---
- name: Template for butane
  ansible.builtin.template:
    src: node.bu.j2
    dest: "{{ _dest }}/{{ ocp_ignition_role }}.bu"
    mode: 0644

- name: Template for butane
  ansible.builtin.command: /usr/local/bin/butane {{ _dest }}/{{ ocp_ignition_role }}.bu -o {{ _dest }}/openshift/{{ ocp_ignition_role }}.yaml
  register: _butane_tpl
  changed_when: "_butane_tpl.rc != 0 and _butane_tpl.stderr != ''"